// app/lib/backlogData.js
export const backlog = [
  {
    id: "zen-1",
    title: "Fix layout issue on mobile view 1",
    type: "bug",
    priority: "Medium",
    status: "In Progress",
    assignee: "Charlie Brown",
    avatar: "https://i.pravatar.cc/40?img=3",
  },
  {
    id: "zen-2",
    title: "Fix layout issue on mobile view 2",
    type: "task",
    priority: "High",
    status: "Review",
    assignee: "Diana Miller",
    avatar: "https://i.pravatar.cc/40?img=4",
  },
  {
    id: "zen-3",
    title: "Fix layout issue on mobile view 3",
    type: "chore",
    priority: "Low",
    status: "Done",
    assignee: "Alice Johnson",
    avatar: "https://i.pravatar.cc/40?img=5",
  },
  {
    id: "zen-4",
    title: "Fix layout issue on mobile view 4",
    type: "bug",
    priority: "Medium",
    status: "To Do",
    assignee: "Bob Williams",
    avatar: "https://i.pravatar.cc/40?img=6",
  },
  {
    id: "zen-5",
    title: "Fix layout issue on mobile view 5",
    type: "task",
    priority: "High",
    status: "In Progress",
    assignee: "Charlie Brown",
    avatar: "https://i.pravatar.cc/40?img=3",
  },
  {
    id: "zen-6",
    title: "Fix layout issue on mobile view 6",
    type: "task",
    priority: "Low",
    status: "Review",
    assignee: "Diana Miller",
    avatar: "https://i.pravatar.cc/40?img=4",
  },
  {
    id: "zen-7",
    title: "Fix layout issue on mobile view 7",
    type: "chore",
    priority: "Medium",
    status: "Done",
    assignee: "Alice Johnson",
    avatar: "https://i.pravatar.cc/40?img=5",
  },
  {
    id: "zen-8",
    title: "Fix layout issue on mobile view 8",
    type: "bug",
    priority: "High",
    status: "To Do",
    assignee: "Bob Williams",
    avatar: "https://i.pravatar.cc/40?img=6",
  },
  // add more items as needed...
];
